# These are supported funding model platforms

# GitHub Sponsors
github: [Refferq]

# Open Collective
# open_collective: refferq

# Patreon
# patreon: refferq

# Ko-fi
# ko_fi: refferq

# Buy Me a Coffee
# ko_fi: refferq

# Custom URLs (up to 4)
# custom: ['https://refferq.com/donate', 'https://paypal.me/refferq']
